baseurl: 'https://agape-openscience-blog.netlify.app/'
title: Agape Open science blog
languageCode: en-us
paginate: '10'
theme: Mainroad
disqusShortname: ''
googleAnalytics: ''
image: images/agapecover.png
Author:
  avatar: img/avatar.png
  bio: We are a group of budding researchers and PhD students who first met during a course focusing on open and collaborative research designed under the project Opening Doors funded by the Horizon 2020 EU programme for research and innovation. 
  name: Agape open science team
Params:
  authorbox: yes
  description: An openscience blog for early career reserchers and open science enthusiasts.
  logo:
    subtitle: An agape initiative
  mainSections:
    - post
    - docs
  opengraph: yes
  pager: yes
  post_meta:
    - date
    - categories
  readmore: no
  sidebar:
    home: right
    list: right
    single: right
    widgets:
      - search
      - recent
      - categories
      - taglist
  twitter_cards: no
  widgets:
    recent_num: 5
    tags_counter: no
# [Params.logo]
#   image = "images/agapecover.png"
#   title = "Mainroad"
#   subtitle = "Just another site"
markup:
  goldmark:
    renderer:
      unsafe: true
